name: Sample Action
description: Sample Composite Action

runs: 
  using: composite
  steps:
    - name: Git clone another repo
      uses: actions/checkout@v4
      with:
        name: stephan-lopes/factory-sensors
        path: .
        ref: main
        token: $GITHUB_TOKEN