name: Sample Action
description: Sample Composite Action

inputs:
  token:
    description: Personal Access Token
    required: true

runs: 
  using: composite
  steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Git clone another repo
      run: |
        git remote add other-repo https://github.com/stephan-lopes/swagger.git
        git fetch other-repo
        git checkout other-repo/main -- .
      shell: bash
    
    - name: execute ls command
      run: ls 
      shell: bash

    - name: Executa o shell.sh
      run: cat shell.sh
      shell: bash