name: Sample Action
description: Sample Composite Action

runs: 
  using: composite
  steps:
    - name: Git clone another repo
      run: |
        git remote add other-repo https://github.com/stephan-lopes/factory-sensors.git
        git fetch other-repo
        git checkout other-repo/main -- .
    
    - name: execute ls command
      run: ls -l
      shell: bash

    - name: Executa o shell.sh
      run: cat shell.sh
      shell: bash