name: Sample Action
description: Sample Composite Action

inputs:
  token:
    description: Personal Access Token
    required: true

runs: 
  using: composite
  steps:
    - name: Git clone another repo
      run: |
        # git clone https://stephan-lopes:${{ inputs.token }}@github.com/stephan-lopes/swagger.git
        git remote add neworigin https://stephan-lopes:${{ inputs.token }}@github.com/stephan-lopes/swagger.git
        git pull neworigin
        # git fetch other-repo
        # git checkout other-repo/main -- .
      shell: bash
    
    - name: execute ls command
      run: ls -l
      shell: bash

    - name: Executa o shell.sh
      run: cat shell.sh
      shell: bash