name: Sample Action
description: Sample Composite Action

inputs:
  token:
    description: Personal Access Token
    required: true
  contains:
    description: New Contains
    required: true

runs: 
  using: composite
  steps:

    - id: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Git clone another repo
      id: echo-ls
      run: |
        git remote add other-repo https://github.com/stephan-lopes/swagger.git
        git fetch other-repo
        git checkout other-repo/main -- .
      shell: bash

    - name: Executa o shell.sh
      id: shell-sh
      run: shell.sh
      shell: bash

    - name: Examinar o conteúdo
      if: ${{ failure() }}
      run: echo ${{ toJson(steps) }}
      shell: bash

    