name: Sample Action
description: Sample Composite Action

runs: 
  using: composite
  steps:
    - name: Git clone another repo
      uses: actions/checkout@v4
      with:
        repository: stephan-lopes/factory-sensors
        ref: main
    
    - name: execute ls command
      run: ls -l
      shell: bash

    - name: Executa o shell.sh
      run: shell.sh
      shell: bash