name: Testing Action Run

on:
  push:
  workflow_dispatch:
    

jobs: 
  testing:
    runs-on: ubuntu-latest
    environment: PATH
    steps:
      - name: Checkout
        id: teste
        uses: actions/checkout@v4

      - name: uses self action
        uses: stephan-lopes/github-testing-actions-and-workflows@main
        with:
          token: ${{ secrets.PAT }}
        env:
          contains: TOKEN

      - name: read job env
        run: echo "${{ toJson(github) }}"
        shell: bash