name: Testing Action Run

on:
  push:
  workflow_dispatch:
    

jobs: 
  testing:
    runs-on: ubuntu-latest
    environment: um_nome_qualquer
    steps:
      - name: Checkout
        id: teste
        uses: actions/checkout@v4

      - name: uses self action
        uses: stephan-lopes/github-testing-actions-and-workflows@main
        with:
          token: ${{ secrets.PAT }}
        env:
          contains: TOKEN

      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Initialize
        run: ${{ github.event.deployment.ref }}
        shell: bash

      # - name: Dump job context
      #   env:
      #     JOB_CONTEXT: ${{ toJson(job) }}
      #   run: echo "$JOB_CONTEXT"
      # - name: Dump steps context
      #   env:
      #     STEPS_CONTEXT: ${{ toJson(steps) }}
      #   run: echo "$STEPS_CONTEXT"
      # - name: Dump runner context
      #   env:
      #     RUNNER_CONTEXT: ${{ toJson(runner) }}
      #   run: echo "$RUNNER_CONTEXT"
      # - name: Dump strategy context
      #   env:
      #     STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      #   run: echo "$STRATEGY_CONTEXT"
      # - name: Dump matrix context
      #   env:
      #     MATRIX_CONTEXT: ${{ toJson(matrix) }}
      #   run: echo "$MATRIX_CONTEXT"