name: Testing Action Run

on:
  push:
  workflow_dispatch:
    

jobs: 
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: teste
        uses: actions/checkout@v3

      - name: Get Outcome
        run: |
          echo ${{ steps.teste.outcome }}
        shell: bash 
