name: Testing Action Run

on:
  push:
  workflow_dispatch:
    

jobs: 
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: teste
        uses: actions/checkout@v4

      - name: uses self action
        uses: ./action.yaml