name: Testing Action Run

on:
  push:
  workflow_dispatch:

env: 
  deployment_name: um_nome_qualquer

jobs: 
  testing:
    runs-on: ubuntu-latest
    environment:
      name: $deployment_name
    steps:
      - name: Checkout
        id: teste
        uses: actions/checkout@v4

      - run: echo ${{ toJson(vars) }}