name: Testing Action Run

on:
  push:
  workflow_dispatch:


env: 
  env_vars:
    deployment_name: um_nome_qualquer


jobs: 
  testing:
    runs-on: ubuntu-latest
    environment:
      name: um_nome_qualquer
    steps:
      - name: Checkout
        id: teste
        uses: actions/checkout@v4

      - run: echo ${{ vars.TESTE }}
        shell: bash